version: '2.3'
services:
  multy-back:
    image: multyio/multy-back:${MULTY_BACK_VERSION}
    env_file: .env
    restart: on-failure
    volumes:
      - "${MULTY_BACK_LOGS}:/go/src/github.com/Multy-io/Multy-back/cmd/logs"
      - "${MULTY_BACK_CONF}:/multy/multy-back.config"
      - "${MULTY_BACK_CURRENCIES}:/currencies"
    ports:
      - "${MULTY_REST_PORT}:6778" 
      - "${MULTY_SOCKETIO_PORT}:6780"
    depends_on:
      - nsq
      - mongodb
      - btc-ns-mainnet
      - btc-ns-testnet
      - eth-ns-mainnet
      - eth-ns-testnet
    expose:
      - 6778
      - 6780

  mongodb:
    container_name: "mongo_db_dev"
    image: mongo:3.6.2
    env_file: .env
    restart: on-failure
    command: mongod --smallfiles --config /mongo/mongod.conf
    volumes:
      - "${MONGO_DATA_DIR}:/data/db"
      - "${MONGO_LOG_DIR}:/data/logs"
      - "${MONGO_CONF_DIR}:/mongo"
      - "./mongo_entrypoint.sh:/mongo_entrypoint.sh"
    expose:
      - "27017"    

  nsqlookup:
    image: nsqio/nsq
    restart: on-failure
    expose:
      - "4160"
    command: nsqlookupd

  nsq:
    image: nsqio/nsq
    hostname: nsq
    restart: on-failure
    expose: 
      - "4150"
    links:
      - nsqlookup
    env_file: .env
    volumes:
      - "${NSQD_DATA_DIR}:/data/nsqd"
    command: nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookup:4160 -data-path=/data

  eth-ns-mainnet:
    image: multyio/multy-eth-node-service:${MULTY_NS_ETH_VERSION}

    restart: on-failure
    hostname: multy.local
    volumes:
      - "${MULTY_NS_ETH_MAINNET_CONFIG}:/multy/ns-eth.config"
    expose:
      - "7744"
    mem_limit: 2G
    memswap_limit: 500MB


  eth-ns-testnet:
    image: multyio/multy-eth-node-service:${MULTY_NS_ETH_VERSION}
    restart: on-failure
    hostname: multy.local
    volumes:
      - "${MULTY_NS_ETH_TESTNET_CONFIG}:/multy/ns-eth.config"
    expose:
      - "6644"
    mem_limit: 2G
    memswap_limit: 500MB