version: '2.4'

# debug stuff, ignore this
x-multy-debug: &multy-debug-ref
  # for debugging with delve
  ports:
    - "2345:2345"
  security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
  cap_add:
      - SYS_PTRACE


services:
  multy-back: &multy-back-ref
    image: multyio/multy-back:${MULTY_BACK_VERSION}
    env_file: .env
    restart: on-failure
    volumes:
      - "${MULTY_BACK_LOGS}:/multy/logs"
      - "${MULTY_BACK_CONF}:/multy/multy-back.config"
      - "${MULTY_BACK_CURRENCIES}:/multy/currencies"
    ports:
      - "${MULTY_REST_PORT}:6778" 
      - "${MULTY_SOCKETIO_PORT}:6780"

    depends_on:
      - nsq
      - mongodb
      - multy-eth-ns-mainnet
    expose:
      - 6778
      - 6780
    mem_limit: 1G
    memswap_limit: 2G


  multy-eth-ns-mainnet: &multy-eth-ns-mainnet-ref
    image: multyio/multy-eth-node-service:${MULTY_NS_ETH_VERSION}
    restart: on-failure
    hostname: multy.local
    volumes:
      - "${MULTY_NS_ETH_MAINNET_CONFIG}:/multy/ns-eth.config"
    expose:
      - "7744"
    mem_limit: 2G
    memswap_limit: 3G


  mongodb:
    image: mongo:3.6.2
    env_file: .env
    restart: on-failure
    command: mongod --smallfiles --noauth
    volumes:
      - "${MONGO_DATA_DIR}:/data/db"
      - "${MONGO_LOG_DIR}:/data/logs"
      - "${MONGO_CONF_DIR}:/mongo"
    expose:
      - "27017"


  nsqlookup:
    image: nsqio/nsq
    restart: on-failure
    expose:
      - "4160"
    command: nsqlookupd


  nsq:
    image: nsqio/nsq
    hostname: nsq
    restart: on-failure
    expose: 
      - "4150"
    links:
      - nsqlookup
    env_file: .env
    volumes:
      - "${NSQD_DATA_DIR}:/data/nsqd"
    command: nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookup:4160 -data-path=/data

  nsqadmin:
    image: nsqio/nsq
    hostname: nsq
    restart: on-failure
    ports:
      - "4161:4171"
    links:
      - nsqlookup
    command: nsqadmin --lookupd-http-address=nsqlookup:4161


############################################################################################################
# HERE GOES STUFF FOR DEBUGGING both multy-back and node services in docker
############################################################################################################
  multy-back-debug:
    <<: *multy-back-ref
    <<: *multy-debug-ref
    image: multy-back:debug
    build:
      context: .
      dockerfile: Dockerfile_debug
      args:
        MULTY_DEBUGGEE: /multy/multy-back

  multy-eth-ns-mainnet-debug:
    <<: *multy-eth-ns-mainnet-ref
    <<: *multy-debug-ref
    image: multy-eth-node-service:debug
    build:
      context: .
      dockerfile: Dockerfile_debug
      args:
        MULTY_DEBUGGEE: /multy/ns-eth