// Code generated by protoc-gen-go. DO NOT EDIT.
// source: streamer.proto

package nsethprotobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionHash struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionHash) Reset()         { *m = TransactionHash{} }
func (m *TransactionHash) String() string { return proto.CompactTextString(m) }
func (*TransactionHash) ProtoMessage()    {}
func (*TransactionHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{0}
}

func (m *TransactionHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionHash.Unmarshal(m, b)
}
func (m *TransactionHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionHash.Marshal(b, m, deterministic)
}
func (m *TransactionHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionHash.Merge(m, src)
}
func (m *TransactionHash) XXX_Size() int {
	return xxx_messageInfo_TransactionHash.Size(m)
}
func (m *TransactionHash) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionHash.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionHash proto.InternalMessageInfo

func (m *TransactionHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type AddressInfo struct {
	Balance              string   `protobuf:"bytes,1,opt,name=Balance,proto3" json:"Balance,omitempty"`
	PendingBalance       string   `protobuf:"bytes,2,opt,name=PendingBalance,proto3" json:"PendingBalance,omitempty"`
	Nonce                uint64   `protobuf:"varint,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressInfo) Reset()         { *m = AddressInfo{} }
func (m *AddressInfo) String() string { return proto.CompactTextString(m) }
func (*AddressInfo) ProtoMessage()    {}
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{1}
}

func (m *AddressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressInfo.Unmarshal(m, b)
}
func (m *AddressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressInfo.Marshal(b, m, deterministic)
}
func (m *AddressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressInfo.Merge(m, src)
}
func (m *AddressInfo) XXX_Size() int {
	return xxx_messageInfo_AddressInfo.Size(m)
}
func (m *AddressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AddressInfo proto.InternalMessageInfo

func (m *AddressInfo) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *AddressInfo) GetPendingBalance() string {
	if m != nil {
		return m.PendingBalance
	}
	return ""
}

func (m *AddressInfo) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type FeeRateEstimation struct {
	VerySlow             uint64   `protobuf:"varint,1,opt,name=VerySlow,proto3" json:"VerySlow,omitempty"`
	Slow                 uint64   `protobuf:"varint,2,opt,name=Slow,proto3" json:"Slow,omitempty"`
	Medium               uint64   `protobuf:"varint,3,opt,name=Medium,proto3" json:"Medium,omitempty"`
	Fast                 uint64   `protobuf:"varint,4,opt,name=Fast,proto3" json:"Fast,omitempty"`
	VeryFast             uint64   `protobuf:"varint,5,opt,name=VeryFast,proto3" json:"VeryFast,omitempty"`
	IsContract           bool     `protobuf:"varint,6,opt,name=isContract,proto3" json:"isContract,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeRateEstimation) Reset()         { *m = FeeRateEstimation{} }
func (m *FeeRateEstimation) String() string { return proto.CompactTextString(m) }
func (*FeeRateEstimation) ProtoMessage()    {}
func (*FeeRateEstimation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{2}
}

func (m *FeeRateEstimation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeRateEstimation.Unmarshal(m, b)
}
func (m *FeeRateEstimation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeRateEstimation.Marshal(b, m, deterministic)
}
func (m *FeeRateEstimation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeRateEstimation.Merge(m, src)
}
func (m *FeeRateEstimation) XXX_Size() int {
	return xxx_messageInfo_FeeRateEstimation.Size(m)
}
func (m *FeeRateEstimation) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeRateEstimation.DiscardUnknown(m)
}

var xxx_messageInfo_FeeRateEstimation proto.InternalMessageInfo

func (m *FeeRateEstimation) GetVerySlow() uint64 {
	if m != nil {
		return m.VerySlow
	}
	return 0
}

func (m *FeeRateEstimation) GetSlow() uint64 {
	if m != nil {
		return m.Slow
	}
	return 0
}

func (m *FeeRateEstimation) GetMedium() uint64 {
	if m != nil {
		return m.Medium
	}
	return 0
}

func (m *FeeRateEstimation) GetFast() uint64 {
	if m != nil {
		return m.Fast
	}
	return 0
}

func (m *FeeRateEstimation) GetVeryFast() uint64 {
	if m != nil {
		return m.VeryFast
	}
	return 0
}

func (m *FeeRateEstimation) GetIsContract() bool {
	if m != nil {
		return m.IsContract
	}
	return false
}

type BlockHeight struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeight) Reset()         { *m = BlockHeight{} }
func (m *BlockHeight) String() string { return proto.CompactTextString(m) }
func (*BlockHeight) ProtoMessage()    {}
func (*BlockHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{3}
}

func (m *BlockHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeight.Unmarshal(m, b)
}
func (m *BlockHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeight.Marshal(b, m, deterministic)
}
func (m *BlockHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeight.Merge(m, src)
}
func (m *BlockHeight) XXX_Size() int {
	return xxx_messageInfo_BlockHeight.Size(m)
}
func (m *BlockHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeight.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeight proto.InternalMessageInfo

func (m *BlockHeight) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ETHTransaction struct {
	Hash                 string             `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	From                 string             `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To                   string             `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	Amount               string             `protobuf:"bytes,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Payload              string             `protobuf:"bytes,5,opt,name=Payload,proto3" json:"Payload,omitempty"`
	GasPrice             uint64             `protobuf:"varint,6,opt,name=GasPrice,proto3" json:"GasPrice,omitempty"`
	GasLimit             uint64             `protobuf:"varint,7,opt,name=GasLimit,proto3" json:"GasLimit,omitempty"`
	Nonce                uint64             `protobuf:"varint,8,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	BlockTime            int64              `protobuf:"varint,9,opt,name=BlockTime,proto3" json:"BlockTime,omitempty"`
	TxpoolTime           int64              `protobuf:"varint,10,opt,name=TxpoolTime,proto3" json:"TxpoolTime,omitempty"`
	BlockHeight          int64              `protobuf:"varint,11,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Resync               bool               `protobuf:"varint,12,opt,name=Resync,proto3" json:"Resync,omitempty"`
	ContractInfo         *SmartContractInfo `protobuf:"bytes,13,opt,name=ContractInfo,proto3" json:"ContractInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ETHTransaction) Reset()         { *m = ETHTransaction{} }
func (m *ETHTransaction) String() string { return proto.CompactTextString(m) }
func (*ETHTransaction) ProtoMessage()    {}
func (*ETHTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{4}
}

func (m *ETHTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ETHTransaction.Unmarshal(m, b)
}
func (m *ETHTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ETHTransaction.Marshal(b, m, deterministic)
}
func (m *ETHTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETHTransaction.Merge(m, src)
}
func (m *ETHTransaction) XXX_Size() int {
	return xxx_messageInfo_ETHTransaction.Size(m)
}
func (m *ETHTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ETHTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ETHTransaction proto.InternalMessageInfo

func (m *ETHTransaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ETHTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ETHTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ETHTransaction) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ETHTransaction) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *ETHTransaction) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *ETHTransaction) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *ETHTransaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ETHTransaction) GetBlockTime() int64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func (m *ETHTransaction) GetTxpoolTime() int64 {
	if m != nil {
		return m.TxpoolTime
	}
	return 0
}

func (m *ETHTransaction) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ETHTransaction) GetResync() bool {
	if m != nil {
		return m.Resync
	}
	return false
}

func (m *ETHTransaction) GetContractInfo() *SmartContractInfo {
	if m != nil {
		return m.ContractInfo
	}
	return nil
}

type SmartContractInfo struct {
	Status               int32                `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Method               *SmartContractCall   `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
	Events               []*SmartContractCall `protobuf:"bytes,3,rep,name=Events,proto3" json:"Events,omitempty"`
	DeployedAddress      string               `protobuf:"bytes,4,opt,name=DeployedAddress,proto3" json:"DeployedAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SmartContractInfo) Reset()         { *m = SmartContractInfo{} }
func (m *SmartContractInfo) String() string { return proto.CompactTextString(m) }
func (*SmartContractInfo) ProtoMessage()    {}
func (*SmartContractInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{5}
}

func (m *SmartContractInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContractInfo.Unmarshal(m, b)
}
func (m *SmartContractInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContractInfo.Marshal(b, m, deterministic)
}
func (m *SmartContractInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContractInfo.Merge(m, src)
}
func (m *SmartContractInfo) XXX_Size() int {
	return xxx_messageInfo_SmartContractInfo.Size(m)
}
func (m *SmartContractInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContractInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContractInfo proto.InternalMessageInfo

func (m *SmartContractInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SmartContractInfo) GetMethod() *SmartContractCall {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *SmartContractInfo) GetEvents() []*SmartContractCall {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *SmartContractInfo) GetDeployedAddress() string {
	if m != nil {
		return m.DeployedAddress
	}
	return ""
}

type SmartContractCall struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Arguments            [][]byte `protobuf:"bytes,2,rep,name=Arguments,proto3" json:"Arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartContractCall) Reset()         { *m = SmartContractCall{} }
func (m *SmartContractCall) String() string { return proto.CompactTextString(m) }
func (*SmartContractCall) ProtoMessage()    {}
func (*SmartContractCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{6}
}

func (m *SmartContractCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContractCall.Unmarshal(m, b)
}
func (m *SmartContractCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContractCall.Marshal(b, m, deterministic)
}
func (m *SmartContractCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContractCall.Merge(m, src)
}
func (m *SmartContractCall) XXX_Size() int {
	return xxx_messageInfo_SmartContractCall.Size(m)
}
func (m *SmartContractCall) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContractCall.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContractCall proto.InternalMessageInfo

func (m *SmartContractCall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SmartContractCall) GetArguments() [][]byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{7}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ReplyInfo struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{8}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ServiceVersion struct {
	Branch               string   `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	Commit               string   `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	Buildtime            string   `protobuf:"bytes,3,opt,name=buildtime,proto3" json:"buildtime,omitempty"`
	Lasttag              string   `protobuf:"bytes,4,opt,name=lasttag,proto3" json:"lasttag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceVersion) Reset()         { *m = ServiceVersion{} }
func (m *ServiceVersion) String() string { return proto.CompactTextString(m) }
func (*ServiceVersion) ProtoMessage()    {}
func (*ServiceVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{9}
}

func (m *ServiceVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceVersion.Unmarshal(m, b)
}
func (m *ServiceVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceVersion.Marshal(b, m, deterministic)
}
func (m *ServiceVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceVersion.Merge(m, src)
}
func (m *ServiceVersion) XXX_Size() int {
	return xxx_messageInfo_ServiceVersion.Size(m)
}
func (m *ServiceVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceVersion proto.InternalMessageInfo

func (m *ServiceVersion) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *ServiceVersion) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *ServiceVersion) GetBuildtime() string {
	if m != nil {
		return m.Buildtime
	}
	return ""
}

func (m *ServiceVersion) GetLasttag() string {
	if m != nil {
		return m.Lasttag
	}
	return ""
}

// ???
type RejectedTxs struct {
	RejectedTxs          []string `protobuf:"bytes,1,rep,name=RejectedTxs,proto3" json:"RejectedTxs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectedTxs) Reset()         { *m = RejectedTxs{} }
func (m *RejectedTxs) String() string { return proto.CompactTextString(m) }
func (*RejectedTxs) ProtoMessage()    {}
func (*RejectedTxs) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{10}
}

func (m *RejectedTxs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectedTxs.Unmarshal(m, b)
}
func (m *RejectedTxs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectedTxs.Marshal(b, m, deterministic)
}
func (m *RejectedTxs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectedTxs.Merge(m, src)
}
func (m *RejectedTxs) XXX_Size() int {
	return xxx_messageInfo_RejectedTxs.Size(m)
}
func (m *RejectedTxs) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectedTxs.DiscardUnknown(m)
}

var xxx_messageInfo_RejectedTxs proto.InternalMessageInfo

func (m *RejectedTxs) GetRejectedTxs() []string {
	if m != nil {
		return m.RejectedTxs
	}
	return nil
}

type TxsToCheck struct {
	Hash                 []string `protobuf:"bytes,1,rep,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxsToCheck) Reset()         { *m = TxsToCheck{} }
func (m *TxsToCheck) String() string { return proto.CompactTextString(m) }
func (*TxsToCheck) ProtoMessage()    {}
func (*TxsToCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{11}
}

func (m *TxsToCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxsToCheck.Unmarshal(m, b)
}
func (m *TxsToCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxsToCheck.Marshal(b, m, deterministic)
}
func (m *TxsToCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxsToCheck.Merge(m, src)
}
func (m *TxsToCheck) XXX_Size() int {
	return xxx_messageInfo_TxsToCheck.Size(m)
}
func (m *TxsToCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_TxsToCheck.DiscardUnknown(m)
}

var xxx_messageInfo_TxsToCheck proto.InternalMessageInfo

func (m *TxsToCheck) GetHash() []string {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{12}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type UsersData struct {
	Map                  map[string]*Address `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UsersData) Reset()         { *m = UsersData{} }
func (m *UsersData) String() string { return proto.CompactTextString(m) }
func (*UsersData) ProtoMessage()    {}
func (*UsersData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b26ab11ddf9501b, []int{13}
}

func (m *UsersData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersData.Unmarshal(m, b)
}
func (m *UsersData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersData.Marshal(b, m, deterministic)
}
func (m *UsersData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersData.Merge(m, src)
}
func (m *UsersData) XXX_Size() int {
	return xxx_messageInfo_UsersData.Size(m)
}
func (m *UsersData) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersData.DiscardUnknown(m)
}

var xxx_messageInfo_UsersData proto.InternalMessageInfo

func (m *UsersData) GetMap() map[string]*Address {
	if m != nil {
		return m.Map
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionHash)(nil), "nsethprotobuf.TransactionHash")
	proto.RegisterType((*AddressInfo)(nil), "nsethprotobuf.AddressInfo")
	proto.RegisterType((*FeeRateEstimation)(nil), "nsethprotobuf.FeeRateEstimation")
	proto.RegisterType((*BlockHeight)(nil), "nsethprotobuf.BlockHeight")
	proto.RegisterType((*ETHTransaction)(nil), "nsethprotobuf.ETHTransaction")
	proto.RegisterType((*SmartContractInfo)(nil), "nsethprotobuf.SmartContractInfo")
	proto.RegisterType((*SmartContractCall)(nil), "nsethprotobuf.SmartContractCall")
	proto.RegisterType((*Address)(nil), "nsethprotobuf.Address")
	proto.RegisterType((*ReplyInfo)(nil), "nsethprotobuf.ReplyInfo")
	proto.RegisterType((*ServiceVersion)(nil), "nsethprotobuf.ServiceVersion")
	proto.RegisterType((*RejectedTxs)(nil), "nsethprotobuf.RejectedTxs")
	proto.RegisterType((*TxsToCheck)(nil), "nsethprotobuf.TxsToCheck")
	proto.RegisterType((*Empty)(nil), "nsethprotobuf.Empty")
	proto.RegisterType((*UsersData)(nil), "nsethprotobuf.UsersData")
	proto.RegisterMapType((map[string]*Address)(nil), "nsethprotobuf.UsersData.MapEntry")
}

func init() { proto.RegisterFile("streamer.proto", fileDescriptor_8b26ab11ddf9501b) }

var fileDescriptor_8b26ab11ddf9501b = []byte{
	// 893 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x6e, 0xe3, 0x36,
	0x10, 0xb6, 0x2c, 0x3b, 0x89, 0xc6, 0x1b, 0xa7, 0x21, 0x82, 0x40, 0x35, 0xda, 0x85, 0xaa, 0x22,
	0x85, 0x0f, 0x45, 0x0a, 0x64, 0x2f, 0x8b, 0xde, 0xb2, 0x8e, 0xe3, 0xa4, 0xe8, 0x06, 0x29, 0xed,
	0xee, 0x9d, 0x91, 0x66, 0x6d, 0x35, 0x92, 0x68, 0x88, 0x74, 0x1a, 0xbf, 0x40, 0xcf, 0x7d, 0x8f,
	0x3e, 0x49, 0x1f, 0xa6, 0xef, 0x50, 0x70, 0x4c, 0xd9, 0xb2, 0xbc, 0xd9, 0xf6, 0x24, 0x7e, 0x1f,
	0x87, 0xc3, 0xf9, 0xf9, 0x38, 0x82, 0xae, 0xd2, 0x05, 0x8a, 0x0c, 0x8b, 0xf3, 0x79, 0x21, 0xb5,
	0x64, 0x87, 0xb9, 0x42, 0x3d, 0xa3, 0xf5, 0xc3, 0xe2, 0x63, 0x78, 0x06, 0x47, 0x93, 0x42, 0xe4,
	0x4a, 0x44, 0x3a, 0x91, 0xf9, 0x8d, 0x50, 0x33, 0xc6, 0xa0, 0x65, 0xbe, 0xbe, 0x13, 0x38, 0x7d,
	0x8f, 0xd3, 0x3a, 0x44, 0xe8, 0x5c, 0xc6, 0x71, 0x81, 0x4a, 0xdd, 0xe6, 0x1f, 0x25, 0xf3, 0x61,
	0xff, 0x9d, 0x48, 0x45, 0x1e, 0xa1, 0xb5, 0x2a, 0x21, 0xfb, 0x0e, 0xba, 0xf7, 0x98, 0xc7, 0x49,
	0x3e, 0x2d, 0x0d, 0x9a, 0x64, 0x50, 0x63, 0xd9, 0x09, 0xb4, 0xef, 0xa4, 0xd9, 0x76, 0x03, 0xa7,
	0xdf, 0xe2, 0x2b, 0x10, 0xfe, 0xe5, 0xc0, 0xf1, 0x35, 0x22, 0x17, 0x1a, 0x87, 0x4a, 0x27, 0x99,
	0x30, 0x41, 0xb1, 0x1e, 0x1c, 0x7c, 0xc0, 0x62, 0x39, 0x4e, 0xe5, 0xef, 0x74, 0x5d, 0x8b, 0xaf,
	0xb1, 0x09, 0x96, 0xf8, 0x26, 0xf1, 0xb4, 0x66, 0xa7, 0xb0, 0xf7, 0x1e, 0xe3, 0x64, 0x91, 0x59,
	0xe7, 0x16, 0x19, 0xdb, 0x6b, 0xa1, 0xb4, 0xdf, 0x5a, 0xd9, 0x9a, 0x75, 0xe9, 0x9b, 0xf8, 0xf6,
	0xc6, 0x37, 0xed, 0xbd, 0x06, 0x48, 0xd4, 0x40, 0xe6, 0xba, 0x10, 0x91, 0xf6, 0xf7, 0x02, 0xa7,
	0x7f, 0xc0, 0x2b, 0x4c, 0x78, 0x06, 0x9d, 0x77, 0xa9, 0x8c, 0x1e, 0x6f, 0x30, 0x99, 0xce, 0xb4,
	0xb9, 0x76, 0x46, 0x2b, 0x0a, 0xd2, 0xe5, 0x16, 0x85, 0x7f, 0xb8, 0xd0, 0x1d, 0x4e, 0x6e, 0x2a,
	0x65, 0xfe, 0x54, 0x89, 0x29, 0xba, 0x42, 0x66, 0xb6, 0x5e, 0xb4, 0x66, 0x5d, 0x68, 0x4e, 0x24,
	0x65, 0xe1, 0xf1, 0xe6, 0x44, 0x9a, 0x2b, 0x2e, 0x33, 0xb9, 0xc8, 0x57, 0x39, 0x78, 0xdc, 0x22,
	0xd3, 0x8f, 0x7b, 0xb1, 0x4c, 0xa5, 0x88, 0x29, 0x09, 0x8f, 0x97, 0xd0, 0xe4, 0x37, 0x12, 0xea,
	0xbe, 0x48, 0x22, 0xa4, 0x0c, 0x5a, 0x7c, 0x8d, 0xed, 0xde, 0xcf, 0x49, 0x96, 0x68, 0x7f, 0x7f,
	0xbd, 0x47, 0x78, 0xd3, 0x9f, 0x83, 0x4a, 0x7f, 0xd8, 0x57, 0xe0, 0x51, 0xc6, 0x93, 0x24, 0x43,
	0xdf, 0xa3, 0x2c, 0x37, 0x84, 0xa9, 0xd7, 0xe4, 0x79, 0x2e, 0x65, 0x4a, 0xdb, 0x40, 0xdb, 0x15,
	0x86, 0x05, 0x5b, 0xf5, 0xf2, 0x3b, 0x64, 0x50, 0x2f, 0x21, 0x47, 0xb5, 0xcc, 0x23, 0xff, 0x15,
	0x55, 0xdb, 0x22, 0x76, 0x05, 0xaf, 0xca, 0xaa, 0x1b, 0xfd, 0xf9, 0x87, 0x81, 0xd3, 0xef, 0x5c,
	0x04, 0xe7, 0x5b, 0x5a, 0x3e, 0x1f, 0x67, 0xa2, 0xd0, 0x55, 0x3b, 0xbe, 0x75, 0x2a, 0xfc, 0xdb,
	0x81, 0xe3, 0x1d, 0x1b, 0x73, 0xe7, 0x58, 0x0b, 0xbd, 0x50, 0xd4, 0x8d, 0x36, 0xb7, 0x88, 0xbd,
	0x35, 0x2a, 0xd2, 0x33, 0x19, 0x53, 0x47, 0xfe, 0xe3, 0xb6, 0x81, 0x48, 0x53, 0x6e, 0xed, 0xcd,
	0xc9, 0xe1, 0x13, 0xe6, 0x5a, 0xf9, 0x6e, 0xe0, 0xfe, 0xbf, 0x93, 0x2b, 0x7b, 0xd6, 0x87, 0xa3,
	0x2b, 0x9c, 0xa7, 0x72, 0x89, 0xb1, 0x7d, 0x6e, 0xb6, 0xd1, 0x75, 0x3a, 0x1c, 0xd6, 0x52, 0x31,
	0x6e, 0x8c, 0x84, 0xee, 0x44, 0x56, 0xbe, 0x49, 0x5a, 0x9b, 0x96, 0x5d, 0x16, 0xd3, 0x45, 0x46,
	0xf1, 0x34, 0x03, 0xb7, 0xff, 0x8a, 0x6f, 0x88, 0xf0, 0x5b, 0xd8, 0xb7, 0x1e, 0x8d, 0x86, 0x84,
	0xbd, 0xd3, 0xbe, 0x69, 0x0b, 0xc3, 0x33, 0xf0, 0x38, 0xce, 0xd3, 0x65, 0xf9, 0xf4, 0x33, 0x54,
	0x4a, 0x4c, 0xd7, 0x4f, 0xdf, 0xc2, 0xf0, 0x19, 0xba, 0x63, 0x2c, 0x9e, 0x92, 0x08, 0x3f, 0x60,
	0xa1, 0x8c, 0xcc, 0x4f, 0x61, 0xef, 0xa1, 0x10, 0x79, 0x54, 0x0a, 0xdd, 0x22, 0xc3, 0x47, 0x32,
	0x33, 0xb2, 0x5b, 0x89, 0xdd, 0x22, 0x13, 0xeb, 0xc3, 0x22, 0x49, 0x63, 0x6d, 0xf4, 0xb3, 0x52,
	0xfd, 0x86, 0x30, 0x37, 0xa7, 0x42, 0x69, 0x2d, 0xa6, 0xb6, 0x28, 0x25, 0x0c, 0x7f, 0x80, 0x0e,
	0xc7, 0xdf, 0x30, 0xd2, 0x18, 0x4f, 0x9e, 0x95, 0xd1, 0x59, 0x05, 0xfa, 0x4e, 0xe0, 0xf6, 0x3d,
	0x5e, 0xa5, 0xc2, 0xc0, 0x28, 0x55, 0x4d, 0xe4, 0x60, 0x86, 0xd1, 0x63, 0xe5, 0x35, 0xba, 0xeb,
	0x81, 0xb7, 0x0f, 0xed, 0x61, 0x36, 0xd7, 0xcb, 0xf0, 0x4f, 0x07, 0xbc, 0x5f, 0x15, 0x16, 0xea,
	0x4a, 0x68, 0xc1, 0xde, 0x80, 0x9b, 0x89, 0x39, 0x59, 0x76, 0x2e, 0xbe, 0xa9, 0xf5, 0x75, 0x6d,
	0x76, 0xfe, 0x5e, 0xcc, 0x87, 0xb9, 0x2e, 0x96, 0xdc, 0x58, 0xf7, 0xee, 0xe0, 0xa0, 0x24, 0xd8,
	0x17, 0xe0, 0x3e, 0xe2, 0xd2, 0xd6, 0xc3, 0x2c, 0xd9, 0xf7, 0xd0, 0x7e, 0x12, 0xe9, 0x02, 0xad,
	0xcc, 0x4e, 0x6b, 0x4e, 0x6d, 0x7b, 0xf8, 0xca, 0xe8, 0xc7, 0xe6, 0x5b, 0xe7, 0xe2, 0x9f, 0x16,
	0xb0, 0x3b, 0x19, 0xe3, 0x40, 0x66, 0xd9, 0x22, 0x4f, 0x22, 0x9a, 0x92, 0x8a, 0xfd, 0x04, 0xc7,
	0x23, 0xd4, 0xb5, 0x16, 0x9c, 0xd4, 0xdc, 0x51, 0x52, 0xbd, 0xaf, 0xeb, 0x8a, 0xdc, 0x3a, 0x14,
	0x36, 0x18, 0x87, 0x93, 0x11, 0xea, 0xdd, 0x51, 0xfc, 0x42, 0x74, 0xbd, 0xba, 0xc4, 0x77, 0x4e,
	0x86, 0x0d, 0x76, 0x0d, 0xdd, 0x11, 0xea, 0xea, 0x6f, 0xe4, 0x25, 0x6f, 0xbd, 0x4f, 0xf3, 0xf4,
	0x88, 0x1b, 0x6c, 0x00, 0x87, 0xab, 0xb1, 0x50, 0x2a, 0xf7, 0x25, 0x37, 0x7e, 0x8d, 0x5f, 0x8b,
	0x38, 0x6c, 0xb0, 0x5b, 0xe8, 0x52, 0xf3, 0x57, 0xaa, 0x30, 0xaa, 0xf9, 0xb2, 0x66, 0xbd, 0x11,
	0xc8, 0x4e, 0x3c, 0x55, 0x29, 0x35, 0xd8, 0x2f, 0x94, 0x57, 0x75, 0xbc, 0xbf, 0xae, 0xbb, 0xda,
	0xfe, 0xc3, 0xee, 0x94, 0x7f, 0xfb, 0xef, 0x40, 0x29, 0x7a, 0xe3, 0x65, 0x1e, 0x99, 0x49, 0x84,
	0xac, 0x7e, 0x7b, 0x65, 0x60, 0x7e, 0x36, 0xc5, 0x11, 0x1c, 0xd1, 0x58, 0xb9, 0xcd, 0x13, 0x9d,
	0x88, 0xf4, 0x32, 0x8e, 0x99, 0xff, 0x92, 0x62, 0x3f, 0xe7, 0xe8, 0x61, 0x8f, 0xd8, 0x37, 0xff,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xce, 0xac, 0x58, 0xaa, 0x4b, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeCommunicationsClient is the client API for NodeCommunications service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeCommunicationsClient interface {
	GetServiceVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceVersion, error)
	GetFeeRateEstimation(ctx context.Context, in *Address, opts ...grpc.CallOption) (*FeeRateEstimation, error)
	GetAddressInfo(ctx context.Context, in *Address, opts ...grpc.CallOption) (*AddressInfo, error)
	ResyncAddress(ctx context.Context, in *Address, opts ...grpc.CallOption) (*ReplyInfo, error)
	CheckRejectTxs(ctx context.Context, in *TxsToCheck, opts ...grpc.CallOption) (*RejectedTxs, error)
	GetTransaction(ctx context.Context, in *TransactionHash, opts ...grpc.CallOption) (*ETHTransaction, error)
	SyncState(ctx context.Context, in *BlockHeight, opts ...grpc.CallOption) (*ReplyInfo, error)
	// TODO: remove
	EventInitialAdd(ctx context.Context, in *UsersData, opts ...grpc.CallOption) (*ReplyInfo, error)
}

type nodeCommunicationsClient struct {
	cc *grpc.ClientConn
}

func NewNodeCommunicationsClient(cc *grpc.ClientConn) NodeCommunicationsClient {
	return &nodeCommunicationsClient{cc}
}

func (c *nodeCommunicationsClient) GetServiceVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceVersion, error) {
	out := new(ServiceVersion)
	err := c.cc.Invoke(ctx, "/nsethprotobuf.NodeCommunications/GetServiceVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) GetFeeRateEstimation(ctx context.Context, in *Address, opts ...grpc.CallOption) (*FeeRateEstimation, error) {
	out := new(FeeRateEstimation)
	err := c.cc.Invoke(ctx, "/nsethprotobuf.NodeCommunications/GetFeeRateEstimation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) GetAddressInfo(ctx context.Context, in *Address, opts ...grpc.CallOption) (*AddressInfo, error) {
	out := new(AddressInfo)
	err := c.cc.Invoke(ctx, "/nsethprotobuf.NodeCommunications/GetAddressInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) ResyncAddress(ctx context.Context, in *Address, opts ...grpc.CallOption) (*ReplyInfo, error) {
	out := new(ReplyInfo)
	err := c.cc.Invoke(ctx, "/nsethprotobuf.NodeCommunications/ResyncAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) CheckRejectTxs(ctx context.Context, in *TxsToCheck, opts ...grpc.CallOption) (*RejectedTxs, error) {
	out := new(RejectedTxs)
	err := c.cc.Invoke(ctx, "/nsethprotobuf.NodeCommunications/CheckRejectTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) GetTransaction(ctx context.Context, in *TransactionHash, opts ...grpc.CallOption) (*ETHTransaction, error) {
	out := new(ETHTransaction)
	err := c.cc.Invoke(ctx, "/nsethprotobuf.NodeCommunications/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) SyncState(ctx context.Context, in *BlockHeight, opts ...grpc.CallOption) (*ReplyInfo, error) {
	out := new(ReplyInfo)
	err := c.cc.Invoke(ctx, "/nsethprotobuf.NodeCommunications/SyncState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) EventInitialAdd(ctx context.Context, in *UsersData, opts ...grpc.CallOption) (*ReplyInfo, error) {
	out := new(ReplyInfo)
	err := c.cc.Invoke(ctx, "/nsethprotobuf.NodeCommunications/EventInitialAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeCommunicationsServer is the server API for NodeCommunications service.
type NodeCommunicationsServer interface {
	GetServiceVersion(context.Context, *Empty) (*ServiceVersion, error)
	GetFeeRateEstimation(context.Context, *Address) (*FeeRateEstimation, error)
	GetAddressInfo(context.Context, *Address) (*AddressInfo, error)
	ResyncAddress(context.Context, *Address) (*ReplyInfo, error)
	CheckRejectTxs(context.Context, *TxsToCheck) (*RejectedTxs, error)
	GetTransaction(context.Context, *TransactionHash) (*ETHTransaction, error)
	SyncState(context.Context, *BlockHeight) (*ReplyInfo, error)
	// TODO: remove
	EventInitialAdd(context.Context, *UsersData) (*ReplyInfo, error)
}

// UnimplementedNodeCommunicationsServer can be embedded to have forward compatible implementations.
type UnimplementedNodeCommunicationsServer struct {
}

func (*UnimplementedNodeCommunicationsServer) GetServiceVersion(ctx context.Context, req *Empty) (*ServiceVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceVersion not implemented")
}
func (*UnimplementedNodeCommunicationsServer) GetFeeRateEstimation(ctx context.Context, req *Address) (*FeeRateEstimation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeeRateEstimation not implemented")
}
func (*UnimplementedNodeCommunicationsServer) GetAddressInfo(ctx context.Context, req *Address) (*AddressInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressInfo not implemented")
}
func (*UnimplementedNodeCommunicationsServer) ResyncAddress(ctx context.Context, req *Address) (*ReplyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResyncAddress not implemented")
}
func (*UnimplementedNodeCommunicationsServer) CheckRejectTxs(ctx context.Context, req *TxsToCheck) (*RejectedTxs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRejectTxs not implemented")
}
func (*UnimplementedNodeCommunicationsServer) GetTransaction(ctx context.Context, req *TransactionHash) (*ETHTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (*UnimplementedNodeCommunicationsServer) SyncState(ctx context.Context, req *BlockHeight) (*ReplyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncState not implemented")
}
func (*UnimplementedNodeCommunicationsServer) EventInitialAdd(ctx context.Context, req *UsersData) (*ReplyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventInitialAdd not implemented")
}

func RegisterNodeCommunicationsServer(s *grpc.Server, srv NodeCommunicationsServer) {
	s.RegisterService(&_NodeCommunications_serviceDesc, srv)
}

func _NodeCommunications_GetServiceVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).GetServiceVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsethprotobuf.NodeCommunications/GetServiceVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).GetServiceVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_GetFeeRateEstimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).GetFeeRateEstimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsethprotobuf.NodeCommunications/GetFeeRateEstimation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).GetFeeRateEstimation(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_GetAddressInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).GetAddressInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsethprotobuf.NodeCommunications/GetAddressInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).GetAddressInfo(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_ResyncAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).ResyncAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsethprotobuf.NodeCommunications/ResyncAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).ResyncAddress(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_CheckRejectTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxsToCheck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).CheckRejectTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsethprotobuf.NodeCommunications/CheckRejectTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).CheckRejectTxs(ctx, req.(*TxsToCheck))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsethprotobuf.NodeCommunications/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).GetTransaction(ctx, req.(*TransactionHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_SyncState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockHeight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).SyncState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsethprotobuf.NodeCommunications/SyncState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).SyncState(ctx, req.(*BlockHeight))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_EventInitialAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).EventInitialAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsethprotobuf.NodeCommunications/EventInitialAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).EventInitialAdd(ctx, req.(*UsersData))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeCommunications_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nsethprotobuf.NodeCommunications",
	HandlerType: (*NodeCommunicationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceVersion",
			Handler:    _NodeCommunications_GetServiceVersion_Handler,
		},
		{
			MethodName: "GetFeeRateEstimation",
			Handler:    _NodeCommunications_GetFeeRateEstimation_Handler,
		},
		{
			MethodName: "GetAddressInfo",
			Handler:    _NodeCommunications_GetAddressInfo_Handler,
		},
		{
			MethodName: "ResyncAddress",
			Handler:    _NodeCommunications_ResyncAddress_Handler,
		},
		{
			MethodName: "CheckRejectTxs",
			Handler:    _NodeCommunications_CheckRejectTxs_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _NodeCommunications_GetTransaction_Handler,
		},
		{
			MethodName: "SyncState",
			Handler:    _NodeCommunications_SyncState_Handler,
		},
		{
			MethodName: "EventInitialAdd",
			Handler:    _NodeCommunications_EventInitialAdd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streamer.proto",
}
